//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommandExtensibilityExample {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommandExtensibilityExampleStringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandExtensibilityExampleStringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommandExtensibilityExample.CommandExtensibilityExampleStringResources", typeof(CommandExtensibilityExampleStringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example command 1.
        /// </summary>
        internal static string ExampleCommand1DisplayName {
            get {
                return ResourceManager.GetString("ExampleCommand1DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of items selected in the Intelligence Portal: {0}.
        /// </summary>
        internal static string ExampleCommand1MessageFormat {
            get {
                return ResourceManager.GetString("ExampleCommand1MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report how many items are currently selected.
        /// </summary>
        internal static string ExampleCommand1Tooltip {
            get {
                return ResourceManager.GetString("ExampleCommand1Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example command 2.
        /// </summary>
        internal static string ExampleCommand2DisplayName {
            get {
                return ResourceManager.GetString("ExampleCommand2DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The portal {0} displaying information about a set.
        /// </summary>
        internal static string ExampleCommand2MessageFormat {
            get {
                return ResourceManager.GetString("ExampleCommand2MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not.
        /// </summary>
        internal static string ExampleCommand2NegativeResponse {
            get {
                return ResourceManager.GetString("ExampleCommand2NegativeResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is.
        /// </summary>
        internal static string ExampleCommand2PositiveResponse {
            get {
                return ResourceManager.GetString("ExampleCommand2PositiveResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report whether the portal is displaying set information.
        /// </summary>
        internal static string ExampleCommand2Tooltip {
            get {
                return ResourceManager.GetString("ExampleCommand2Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example inserted command.
        /// </summary>
        internal static string ExampleInsertedCommandDisplayName {
            get {
                return ResourceManager.GetString("ExampleInsertedCommandDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command was successfully inserted into the list.
        /// </summary>
        internal static string ExampleInsertedCommandMessage {
            get {
                return ResourceManager.GetString("ExampleInsertedCommandMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display a diagnostic message.
        /// </summary>
        internal static string ExampleInsertedCommandTooltip {
            get {
                return ResourceManager.GetString("ExampleInsertedCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example group heading.
        /// </summary>
        internal static string GroupHeading {
            get {
                return ResourceManager.GetString("GroupHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A group of custom commands from the extensibility example.
        /// </summary>
        internal static string GroupHeadingTooltip {
            get {
                return ResourceManager.GetString("GroupHeadingTooltip", resourceCulture);
            }
        }
    }
}
